ALTER TYPE "PollElementType" ADD VALUE 'SINGLE_SELECTION_GRID';
ALTER TYPE "PollElementType" ADD VALUE 'MULTIPLE_SELECTION_GRID';
ALTER TYPE "PollElementType" ADD VALUE 'SELECTION_DROPDOWN';
ALTER TYPE "PollElementType" ADD VALUE 'LINEAR_SCALE';
ALTER TYPE "PollElementType" ADD VALUE 'STAR_RATING';
ALTER TYPE "PollElementType" ADD VALUE 'DATE';
ALTER TYPE "PollElementType" ADD VALUE 'TIME';

ALTER TABLE "PollElement" ADD COLUMN "settings" JSONB;
